sudo: false
language: python
python: 3.6
os:
  - linux
#  - osx
env:
  - TOX_ENV=py36
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
install:
  - pip install tox
  - pip install coveralls
before_script:
  - wget 'https://releases.hashicorp.com/consul/0.8.4/consul_0.8.4_linux_amd64.zip'
  - unzip "consul_0.8.4_linux_amd64.zip"
  - ./consul agent -dev &
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
