sudo: false
language: python
cache: pip
python: 3.8
os:
  - linux
#  - osx
services:
  - docker
env:
  global:
    - PYTHONUNBUFFERED=True
    - COVERALLS_PARALLEL=true
  jobs:
    - TOX_ENV=py38-integration
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
services:
  - rabbitmq
install:
  - pip install tox
  - pip install tox-docker>=2.0.0a3
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls -v
notifications:
    webhooks:
      - 'https://coveralls.io/webhook'
