apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  namespace: cloudman

spec:
  ports:
  - name: web
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: web
  type: NodePort
