---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: cm-web-service
  namespace: cloudman
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - name: nginx-port
    protocol: TCP
    port: 8008
    targetPort: 80
