apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: cloudman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
      name: web
    spec:
      containers:
      - image: afgane/cloudman:latest
        command:
        - ./run_web.sh
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 8000
          name: web
          protocol: TCP
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
