---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cm-web-deployment
  namespace: cloudman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
      name: cm-web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/cloudman.conf
          subPath: cloudman.conf
      - image: afgane/cloudman:latest
        command:
        - ./run_web.sh
        imagePullPolicy: Always
        name: cm-api
        ports:
        - containerPort: 8000
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
